default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  reconnect: false

development:
  <<: *default
  database: surveyor
  username: postgres
  password: qburst
  host: localhost

test:
  <<: *default
  database: surveyor
  username: sooraj
  password: qburst
  host: localhost

production:
  <<: *default
  database: surveyor
  username: postgres
  password: qburst
  host: localhost
